export const MOCK_PATIENTS = [
    {
        id: "hp_001",
        first_name: "John",
        last_name: "Doe",
        birthDate: "1980-05-15",
        gender: "Male",
        phone: "+1 555-0101",
        email: "john.doe@example.com",
        demographic: "43yo Male",
        current_medications: "Lisinopril 10mg",
        allergies: "Penicillin",
        past_medical_history: "Hypertension, T2DM",
        additional_context: "Patient prefers morning appointments.",
        runStatus: "NOT_RUN"
    },
    {
        id: "hp_002",
        first_name: "Jane",
        last_name: "Smith",
        birthDate: "1992-08-22",
        gender: "Female",
        phone: "+1 555-0102",
        email: "jane.smith@example.com",
        demographic: "31yo Female",
        current_medications: "None",
        allergies: "None",
        past_medical_history: "Asthma",
        additional_context: "",
        runStatus: "IN_FLOW"
    },
    {
        id: "hp_003",
        first_name: "Robert",
        last_name: "Johnson",
        birthDate: "1955-12-10",
        gender: "Male",
        phone: "+1 555-0103",
        email: "bob.j@example.com",
        demographic: "68yo Male",
        current_medications: "Atorvastatin 20mg, Metformin 500mg",
        allergies: "Sulfa drugs",
        past_medical_history: "Hyperlipidemia, Pre-diabetes",
        additional_context: "Hard of hearing.",
        runStatus: "COMPLETED"
    },
    {
        id: "hp_004",
        first_name: "Emily",
        last_name: "Davis",
        birthDate: "1988-03-30",
        gender: "Female",
        phone: "+1 555-0104",
        email: "emily.d@example.com",
        demographic: "35yo Female",
        current_medications: "Sertraline 50mg",
        allergies: "Peanuts",
        past_medical_history: "Anxiety",
        additional_context: "",
        runStatus: "NOT_RUN"
    },
    {
        id: "hp_005",
        first_name: "Michael",
        last_name: "Brown",
        birthDate: "1970-11-05",
        gender: "Male",
        phone: "+1 555-0105",
        email: "m.brown@example.com",
        demographic: "53yo Male",
        current_medications: "None",
        allergies: "None",
        past_medical_history: "Appendectomy (2005)",
        additional_context: "New patient.",
        runStatus: "NOT_RUN"
    }
];
